version: "3.8"

services:
  minecraft:
    # Container Image on dockerhub 
    image: itzg/minecraft-server
    tty: true
    stdin_open: true
    # Port Mappings
    ports:
      - "25565:25565"
    # Environment Variables
    environment:
      EULA: "TRUE"
    volumes:
      # attach the relative directory 'data' to the container's /data path
      - F:\mcdata:/data
    # restart policy - attempt to restart 3 times if the container fails
    restart: on-failure:3